import DefaultLayout from './DefaultLayout'
import NoSidebarLayout from './NoSidebarLayout'

import 'antd/dist/antd.css'
import {
    Layout,
    Breadcrumb,
    Image,
    Tag,
    PageHeader,
    Typography,
    Form,
    Avatar,
    Space,
    Divider,
    Card,
    Modal,
    Dropdown,
    Input,
    Drawer,
    List,
    Affix,
    Carousel,
    Comment,
    Row,
    Alert,
    Col,
    Tabs,
    Menu,
    Checkbox,
    Upload,
    message,
    Table,
    Rate,
    Button,
    Select,
} from 'antd'
import {
    PhoneOutlined,
    HeartOutlined,
    UsergroupAddOutlined,
    BookOutlined,
    DownOutlined,
    EnvironmentOutlined,
    HomeOutlined,
    FacebookOutlined,
    ClockCircleOutlined,
    DiffOutlined,
    ReadOutlined,
    MessageOutlined,
    LockOutlined,
    UploadOutlined,
    UserOutlined,
    CaretLeftOutlined,
    CaretRightOutlined,
    BellOutlined,
    EyeOutlined,
    SwapOutlined,
    UserSwitchOutlined,
    LeftCircleOutlined,
} from '@ant-design/icons'

const { Header, Footer, Content, Sider } = Layout
const { Paragraph, Title, Text, Link } = Typography
const { TextArea, Search } = Input
const { Option } = Select
const { TabPane } = Tabs
const constants = {
    Content,
    Paragraph,
    Title,
    TabPane,
    Comment,
    Tabs,
    Rate,
    Dropdown,
    ClockCircleOutlined,
    Table,
    Text,
    HomeOutlined,
    Drawer,
    List,
    DiffOutlined,
    Alert,
    UserOutlined,
    LockOutlined,
    Link,
    ReadOutlined,
    TextArea,
    message,
    Modal,
    Upload,
    Option,
    Form,
    PhoneOutlined,
    DownOutlined,
    Carousel,
    HeartOutlined,
    CaretRightOutlined,
    LeftCircleOutlined,
    UsergroupAddOutlined,
    BookOutlined,
    EnvironmentOutlined,
    FacebookOutlined,
    SwapOutlined,
    UserSwitchOutlined,
    Layout,
    Breadcrumb,
    Image,
    Checkbox,
    Tag,
    Affix,
    BellOutlined,
    PageHeader,
    Menu,
    Typography,
    Avatar,
    EyeOutlined,
    Search,
    CaretLeftOutlined,
    UploadOutlined,
    Space,
    Divider,
    Card,
    Input,
    Row,
    Col,
    Button,
    Select,
    MessageOutlined,
    Header,
    Footer,
    Sider,
}

export { DefaultLayout, NoSidebarLayout, constants }
